version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami'
    environment:
      - MONGODB_USERNAME=<username>
      - MONGODB_PASSWORD=<password>
      - MONGODB_DATABASE=<dbname>

volumes:
  mongodb_data:
    driver: local