version: "3.1"

services:

  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: navneetlalg
      MONGO_INITDB_ROOT_PASSWORD: password123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on: 
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: navneetlalg
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123

  app:
    build: .
    depends_on:
      - mongo
    restart: always
  proxy:
    image: nginx:alpine
    depends_on: 
      - app
    ports: 
      - 80:80
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  mongodb_data:
    driver: local
